src/analytics/analytics.controller.ts, src/analytics/analytics.service.ts, src/analytics/dto/getData.dto.ts, src/user/entities/user.entity.ts
Related to:
- https://github.com/Swetrix/swetrix-fe/pull/38
=> (feature) Timezone setting

src/user/entities/user.entity.ts, src/user/user.controller.ts, src/webhook/webhook.controller.ts
Task:
- https://github.com/Swetrix/roadmap/issues/48
=> Support for yearly billing & other improvements

.env.example, src/app.module.ts, src/marketplace/categories/categories.controller.spec.ts, src/marketplace/categories/categories.controller.ts, src/marketplace/categories/categories.module.ts, src/marketplace/categories/categories.service.spec.ts, src/marketplace/categories/categories.service.ts, src/marketplace/categories/category.entity.ts, src/marketplace/categories/dtos/create-category.dto.ts, src/marketplace/categories/dtos/delete-category-params.dto.ts, src/marketplace/categories/dtos/get-categories-queries.dto.ts, src/marketplace/categories/dtos/get-category-params.dto.ts, src/marketplace/categories/dtos/update-category-params.dto.ts, src/marketplace/categories/dtos/update-category.dto.ts, src/marketplace/categories/interfaces/create-category.interface.ts, src/marketplace/categories/interfaces/save-category.interface.ts, src/marketplace/categories/interfaces/update-category.interface.ts, src/marketplace/categories/pipes/body-validation.pipe.ts, src/marketplace/marketplace.module.ts
https://github.com/Swetrix/roadmap/issues/65
=> marketplace - categories

src/marketplace/extensions/dtos/search-extension-queries.dto.ts, src/marketplace/extensions/extensions.controller.ts
Added a route to search for extensions with panigation.
=> (marketplace - extensions) added a search route

src/analytics/analytics.service.ts, src/app.module.ts, src/common/utils.ts, src/marketplace/categories/categories.controller.ts, src/marketplace/categories/category.entity.ts, src/marketplace/extensions/extension.entity.ts
=> (marketplace - extensions) adding and updating extension categories

src/analytics/analytics.service.ts, src/app.module.ts, src/common/utils.ts, src/marketplace/categories/categories.controller.ts, src/marketplace/categories/category.entity.ts, src/marketplace/extensions/extension.entity.ts
Reverts Swetrix/swetrix-api#54
=> Revert "(marketplace - extensions) adding and updating extension categories"

src/marketplace/categories/categories.controller.ts, src/marketplace/categories/categories.service.ts
=> Performed refactoring of the category controller

src/marketplace/comments/dtos/bodies/create-comment.dto.ts, src/marketplace/complaints/complaints.controller.spec.ts, src/marketplace/complaints/complaints.controller.ts, src/marketplace/complaints/complaints.module.ts, src/marketplace/complaints/complaints.service.spec.ts, src/marketplace/complaints/complaints.service.ts, src/marketplace/complaints/dtos/bodies/create-complaint.dto.ts, src/marketplace/complaints/dtos/bodies/resolve-complaint.dto.ts, src/marketplace/complaints/dtos/params/get-complaint.dto.ts, src/marketplace/complaints/dtos/params/resolve-complaint.dto.ts, src/marketplace/complaints/dtos/queries/create-complaint.dto.ts, src/marketplace/complaints/dtos/queries/get-complaints.dto.ts, src/marketplace/complaints/entities/complaint.entity.ts, src/marketplace/complaints/enums/complaint-status.enum.ts, src/marketplace/extensions/entities/extension.entity.ts, src/marketplace/marketplace.module.ts, src/user/entities/user.entity.ts
https://github.com/Swetrix/roadmap/issues/69
=> (feature) complaints

src/marketplace/extensions/dtos/create-extension.dto.ts, src/marketplace/extensions/dtos/update-extension.dto.ts, src/marketplace/extensions/extensions.controller.ts
add versioning for update extension and set default for create
=> add versioning 

src/alert/alert.controller.ts, src/alert/alert.module.ts, src/alert/alert.service.spec.ts, src/alert/alert.service.ts, src/alert/dto/alert.dto.ts, src/alert/entity/alert.entity.ts, src/analytics/analytics.controller.ts, src/analytics/analytics.service.ts, src/app.module.ts, src/auth/auth.controller.ts, src/project/dto/project.dto.ts, src/project/entity/project.entity.ts, src/project/project.controller.ts, src/project/project.service.ts, src/task-manager/task-manager.module.ts, src/task-manager/task-manager.service.ts, src/tg-integration/constants.ts, src/tg-integration/tg.module.ts, src/tg-integration/tg.update.ts, src/user/dto/admin-update-user.dto.ts, src/user/dto/update-user.dto.ts, src/user/entities/user.entity.ts, src/user/user.controller.ts
Ticket: https://github.com/Swetrix/roadmap/issues/11
=> (feature) Telegram bot

src/tg-integration/tg.update.ts
https://github.com/Swetrix/roadmap/issues/120
=> Added the ability to unlink chat

src/marketplace/extensions/entities/extension-to-project.entity.ts, src/marketplace/extensions/entities/extension.entity.ts, src/marketplace/extensions/extensions.service.ts, src/task-manager/task-manager.module.ts, src/task-manager/task-manager.service.ts
https://github.com/Swetrix/roadmap/issues/71
=> Added a smart extension tagging system

src/analytics/analytics.controller.ts, src/analytics/analytics.service.ts, src/analytics/dto/get-custom-events.dto.ts, src/project/project.controller.ts, src/project/project.service.ts
https://github.com/Swetrix/roadmap/issues/114
=> (feature) An ability to display custom events on chart

src/analytics/analytics.controller.ts, src/analytics/analytics.service.spec.ts, src/analytics/analytics.service.ts
Ticket: https://github.com/Swetrix/roadmap/issues/137
=> (improvement) Heartbeat session handling

apps/production/src/user/entities/user.entity.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.service.ts, apps/production/src/webhook/webhook.controller.ts, migrations/mysql/2023_05_22.sql
Ticket: https://github.com/Swetrix/roadmap/issues/158
=> (feature) Currency localisation

apps/production/src/project/project.service.ts, apps/selfhosted/src/project/project.service.ts, package.json
=> using built-in nodejs net module instead of validate-ip-node

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/get-filters.dto.ts, apps/production/src/project/project.controller.ts, apps/production/src/project/project.service.ts, meta/clickhouse/generate-dummy-data.js
=> Delete data via filters

.gitignore, apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/common/constants.ts, apps/production/src/common/utils.ts, meta/clickhouse/generate-dummy-data.js, migrations/clickhouse/2023_05_19.js, migrations/clickhouse/2023_06_26.js, package.json
=> (feature) Cities & regions

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/interfaces/index.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/interfaces/index.ts
=> (fix) Custom Event filtering

docker-compose-dev.yml
=> (improvement) Missing Docker service for the development environment

.env.example, apps/production/src/user/dto/change-plan.dto.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.module.ts, apps/production/src/user/user.service.ts, package.json
Ticket: https://github.com/Swetrix/roadmap/issues/164
PR Checklist:
=> (improvement) Pro-rata subscription upgrades

apps/selfhosted/src/project/project.service.ts
=> some update

apps/production/src/auth/auth.module.ts, apps/production/src/auth/auth.service.ts, apps/production/src/integrations/telegram/entities/message.entity.ts, apps/production/src/integrations/telegram/telegram.module.ts, apps/production/src/integrations/telegram/telegram.service.ts, apps/production/src/task-manager/task-manager.module.ts, apps/production/src/task-manager/task-manager.service.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.module.ts, migrations/mysql/2023_07_06.sql
=> (fix) Preventing a Telegram overlimit error

apps/production/src/common/constants.ts, apps/production/src/main.ts
=> (improvement) Ignoring errors for Sentry

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts
=> fast fix all period

apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/getData.dto.ts
=> (feature) 'minute' time bucket

apps/production/src/analytics/analytics.service.ts, migrations/clickhouse/2023_05_07.js
=> (improvement) Minute TB

apps/production/src/auth/auth.service.ts
=> (fix) Error with invalid Google token

apps/production/src/alert/dto/alert.dto.ts
=> (fix) Preventing an error due to lack of validation

.env.example, apps/production/src/analytics/analytics.controller.ts, apps/production/src/common/constants.ts, apps/production/src/common/utils.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/get-filters.dto.ts, apps/selfhosted/src/analytics/dto/getData.dto.ts, apps/selfhosted/src/auth/auth.controller.ts, apps/selfhosted/src/common/constants.ts, apps/selfhosted/src/common/utils.ts, apps/selfhosted/src/project/project.controller.ts, docker-compose.yml
=> (improvement) Preparing for the next selfhosted release

apps/production/src/project/project.controller.ts
=> fix get shared project

apps/production/src/analytics/analytics.service.ts, apps/production/src/project/project.service.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/project/project.service.ts
PR Checklist:
Ticket: https://github.com/Swetrix/roadmap/issues/168
=> (feature) Anonymous pages

apps/production/src/user/user.controller.ts
=> (fix) Updated 'update current user' route

apps/production/src/user/dto/delete-self.dto.ts, apps/production/src/user/entities/delete-feedback.entity.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.module.ts, apps/production/src/user/user.service.ts, migrations/mysql/2023_09_08.sql
PR Checklist:
Ticket:
- https://github.com/Swetrix/roadmap/issues/161
=> (feature) Account deletion feedback

apps/production/src/task-manager/task-manager.service.ts
PR Checklist:
Ticket:
- https://github.com/Swetrix/roadmap/issues/165
=> (improvement) Reset email report frequency for inactive users

apps/production/src/alert/alert.controller.ts, apps/production/src/alert/alert.service.ts, apps/production/src/alert/dto/alert.dto.ts, apps/production/src/alert/entity/alert.entity.ts, apps/production/src/analytics/analytics.controller.ts, apps/production/src/app.module.ts, apps/production/src/captcha/captcha.service.ts, apps/production/src/marketplace/extensions/extensions.controller.ts, apps/production/src/project/project.service.ts, apps/production/src/task-manager/task-manager.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, migrations/mysql/2023_08_09.sql
=> (feature) Alerts for custom events

.env.example, apps/production/src/auth/auth.controller.ts, apps/production/src/auth/auth.service.ts, apps/production/src/auth/dtos/register.dto.ts, apps/production/src/auth/dtos/sso-get-jwt-by-hash.dto.ts, apps/production/src/common/constants.ts, apps/production/src/common/templates/en/paypal-email-update.html, apps/production/src/common/utils.ts, apps/production/src/mailer/letter.ts, apps/production/src/mailer/mailer.service.ts, apps/production/src/payouts/entities/payouts.entity.ts, apps/production/src/payouts/payouts.module.ts, apps/production/src/payouts/payouts.service.ts, apps/production/src/project/entity/project.entity.ts, apps/production/src/task-manager/task-manager.module.ts, apps/production/src/task-manager/task-manager.service.ts, apps/production/src/user/dto/update-user.dto.ts, apps/production/src/user/dto/user-github.dto.ts, apps/production/src/user/dto/user-google.dto.ts, apps/production/src/user/entities/user.entity.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.module.ts, apps/production/src/user/user.service.ts, apps/production/src/webhook/webhook.controller.ts, apps/production/src/webhook/webhook.module.ts, apps/production/src/webhook/webhook.service.ts, migrations/mysql/2023_10_01.sql, package.json
PR Checklist:
Ticket:
- https://github.com/Swetrix/roadmap/issues/147
=> (feature) Referral program

apps/production/src/user/entities/user.entity.ts, migrations/mysql/2023_10_02.sql
=> (improvement) Added new tiers & increased alerts and projects limit

apps/production/src/project/project.controller.ts
=> (feature) project search

apps/production/src/project/project.controller.ts, apps/production/src/user/entities/user.entity.ts, migrations/mysql/2023_10_06.sql
=> (improvement) Move maxprojects to user table

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/events.dto.ts, apps/production/src/analytics/dto/get-custom-event-meta.dto.ts, apps/production/src/analytics/interfaces/index.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/events.dto.ts, apps/selfhosted/src/analytics/dto/get-custom-event-meta.dto.ts, apps/selfhosted/src/analytics/interfaces/index.ts, migrations/clickhouse/2023_10_13.js, migrations/clickhouse/initialise_database.js
PR Checklist:
Ticket:
- https://github.com/Swetrix/roadmap/issues/141
=> (feature) Custom events metadata

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/getData.dto.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/getData.dto.ts
=> (feature) Cumulative mode

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/interfaces/index.ts, apps/production/src/integrations/telegram/scene/projects.scene.ts, apps/production/src/project/project.service.ts, apps/production/src/task-manager/task-manager.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/interfaces/index.ts
=> (improvement) Enhanced `GET /log/birdseye`

apps/production/src/app.module.ts, apps/production/src/og-image/og-image.controller.ts, apps/production/src/og-image/og-image.module.ts, apps/production/src/og-image/og-image.service.ts, apps/production/src/project/project.controller.ts, apps/production/src/project/project.service.ts
=> (feature) Opengraph image generator

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/get-session.dto.ts, apps/production/src/analytics/dto/get-sessions.dto.ts, apps/production/src/analytics/interfaces/index.ts, apps/production/src/task-manager/task-manager.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/get-session.dto.ts, apps/selfhosted/src/analytics/dto/get-sessions.dto.ts, apps/selfhosted/src/analytics/interfaces/index.ts
=> (feature) Session overview / Clickstream

apps/production/src/alert/alert.controller.ts, apps/production/src/auth/auth.controller.ts, apps/production/src/main.ts, apps/production/src/marketplace/categories/categories.controller.ts, apps/production/src/marketplace/complaints/complaints.controller.ts, apps/production/src/marketplace/extensions/extensions.controller.ts, apps/production/src/project/project.controller.ts, apps/production/src/twoFactorAuth/twoFactorAuth.controller.ts, apps/production/src/user/user.controller.ts, apps/selfhosted/src/project/project.controller.ts, apps/selfhosted/src/user/user.controller.ts
Add `@ApiBearerAuth()` for auth within swagger.
=> add ApiBearerAuth decorator for swagger auth

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/interfaces/index.ts, apps/production/src/common/utils.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/interfaces/index.ts, apps/selfhosted/src/common/utils.ts
=> (improvement) Performance metrics

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts
=> (improvement) Performance birdseye measures support

.devcontainer/devcontainer.json, .vscode/extensions.json, apps/production/src/app.module.ts
=> (improvement) Automatic database synchronization

.env.example, Dockerfile.prod, apps/production/src/app.module.ts, apps/production/src/common/constants.ts, apps/production/src/common/templates/en/customer_sign-up.html, apps/production/src/common/templates/en/project-report.html, apps/production/src/mailer/mailer.service.ts, apps/production/src/main.ts, apps/production/src/project/project.controller.ts, apps/production/src/project/project.service.ts, apps/production/src/task-manager/task-manager.service.ts, apps/production/src/user/user.controller.ts, apps/production/src/user/user.service.ts, apps/production/src/webhook/webhook.controller.ts, apps/production/src/webhook/webhook.service.ts, docker-compose-prod.yml, package.json
=> (improvement) Migrate from postmark to AWS SES

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts
=> (improvement) Timezone support for sessions

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts
=> (fix) Errors API timezones support

apps/production/src/analytics/analytics.controller.ts, apps/production/src/analytics/analytics.service.ts, apps/production/src/analytics/dto/events.dto.ts, apps/production/src/analytics/dto/get-custom-event-meta.dto.ts, apps/production/src/analytics/dto/get-page-property-meta.dto.ts, apps/production/src/analytics/dto/pageviews.dto.ts, apps/production/src/analytics/interfaces/index.ts, apps/production/src/common/constants.ts, apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/events.dto.ts, apps/selfhosted/src/analytics/dto/get-page-property-meta.dto.ts, apps/selfhosted/src/analytics/dto/pageviews.dto.ts, apps/selfhosted/src/analytics/interfaces/index.ts, apps/selfhosted/src/common/constants.ts, migrations/clickhouse/2024_06_22.js, migrations/clickhouse/initialise_database.js
=> (feature) Pageview tags

apps/production/src/project/project.controller.ts
=> (fix) Fixed receiving projects with API key

apps/selfhosted/src/analytics/analytics.controller.ts, apps/selfhosted/src/analytics/analytics.service.ts, apps/selfhosted/src/analytics/dto/getData.dto.ts, apps/selfhosted/src/common/utils.ts, apps/selfhosted/src/project/dto/create-project-view.dto.ts, apps/selfhosted/src/project/dto/project-id.dto.ts, apps/selfhosted/src/project/dto/project-view-id.dto.ts, apps/selfhosted/src/project/dto/project-view-ids.dto.ts, apps/selfhosted/src/project/dto/update-project-view.dto.ts, apps/selfhosted/src/project/entity/project-view-custom-event.entity.ts, apps/selfhosted/src/project/entity/project-view.entity.ts, apps/selfhosted/src/project/project.controller.ts, apps/selfhosted/src/project/project.service.ts, migrations/clickhouse/initialise_selfhosted.js, migrations/clickhouse/selfhosted_2024_08_10.js
https://github.com/Swetrix/roadmap/issues/188
=> (improvement) Support for project views on selfhosted instances

web/app/pages/Project/View/Panels.tsx
https://github.com/Swetrix/roadmap/issues/226
=> (feature) Metadata table sorting

backend/apps/production/src/task-manager/task-manager.service.ts
https://github.com/Swetrix/swetrix/issues/260
=> (fix) Alert condition calculation

backend/apps/production/src/analytics/analytics.controller.ts, backend/apps/production/src/analytics/analytics.service.ts, backend/apps/production/src/analytics/utils/transformers.ts, backend/apps/production/src/integrations/telegram/scene/projects.scene.ts, backend/apps/production/src/task-manager/task-manager.service.ts, backend/apps/selfhosted/src/analytics/analytics.controller.ts, backend/apps/selfhosted/src/analytics/analytics.service.ts, backend/apps/selfhosted/src/analytics/utils/transformers.ts, backend/apps/selfhosted/src/task-manager/task-manager.service.ts, backend/migrations/clickhouse/2024_10_15.js, backend/migrations/clickhouse/initialise_database.js, web/app/api/index.ts, web/app/pages/Project/View/ViewProject.tsx, web/app/pages/Project/View/components/CountryDropdown.tsx, web/app/pages/Project/View/components/CustomEventsDropdown.tsx, web/app/pages/Project/View/components/LiveVisitorsDropdown.tsx, web/app/pages/Project/View/components/MetricCards.tsx, web/app/pages/Project/View/components/Pageflow.tsx, web/app/pages/Project/View/components/UTMDropdown.tsx, web/package.json
On deploy, delete old session hashes:
`redis-cli KEYS "sd:ses_*" | xargs redis-cli DEL`
`redis-cli KEYS "hb:*" | xargs redis-cli DEL`
https://github.com/Swetrix/swetrix/issues/262
=> (improvement) Online users count rework

backend/apps/production/src/analytics/analytics.controller.ts, backend/apps/production/src/analytics/analytics.service.ts, backend/apps/production/src/analytics/dto/get-custom-event-meta.dto.ts, backend/apps/production/src/analytics/dto/get-custom-events.dto.ts, backend/apps/production/src/analytics/dto/get-error.dto.ts, backend/apps/production/src/analytics/dto/get-errors.dto.ts, backend/apps/production/src/analytics/dto/get-monitor-data.dto.ts, backend/apps/production/src/analytics/dto/get-page-property-meta.dto.ts, backend/apps/production/src/analytics/dto/get-sessions.dto.ts, backend/apps/production/src/analytics/dto/getData.dto.ts, backend/apps/selfhosted/src/analytics/analytics.controller.ts, backend/apps/selfhosted/src/analytics/analytics.service.ts, backend/apps/selfhosted/src/analytics/dto/get-custom-event-meta.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-custom-events.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-error.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-errors.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-page-property-meta.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-sessions.dto.ts, backend/apps/selfhosted/src/analytics/dto/getData.dto.ts
https://github.com/Swetrix/swetrix/issues/273
=> (improvement) Move timebucket validation to the DTO

backend/apps/production/src/analytics/analytics.controller.ts, backend/apps/production/src/analytics/analytics.service.ts, backend/apps/production/src/analytics/decorators/validate-period.decorator.ts, backend/apps/production/src/analytics/dto/get-monitor-data.dto.ts, backend/apps/production/src/analytics/dto/get-overall-stats.dto.ts, backend/apps/production/src/analytics/dto/get-uptime-birdseye.dto.ts, backend/apps/production/src/analytics/dto/getData.dto.ts, backend/apps/production/src/analytics/dto/getFunnels.dto.ts, backend/apps/production/src/analytics/dto/getUserFlow.dto.ts, backend/apps/production/src/project/project.controller.ts, backend/apps/selfhosted/src/analytics/analytics.controller.ts, backend/apps/selfhosted/src/analytics/analytics.service.ts, backend/apps/selfhosted/src/analytics/decorators/validate-period.decorator.ts, backend/apps/selfhosted/src/analytics/dto/get-overall-stats.dto.ts, backend/apps/selfhosted/src/analytics/dto/get-page-property-meta.dto.ts, backend/apps/selfhosted/src/analytics/dto/getData.dto.ts, backend/apps/selfhosted/src/analytics/dto/getFunnels.dto.ts, backend/apps/selfhosted/src/analytics/dto/getUserFlow.dto.ts, backend/apps/selfhosted/src/project/project.controller.ts
https://github.com/Swetrix/swetrix/issues/274
=> (improvement) Move period validation to DTO

backend/apps/production/src/analytics/analytics.controller.ts, backend/apps/production/src/analytics/analytics.service.ts, backend/apps/production/src/analytics/utils/transformers.ts, backend/apps/production/src/project/project.controller.ts, backend/apps/production/src/project/project.service.ts, backend/apps/production/src/task-manager/task-manager.service.ts, backend/apps/production/src/user/user.controller.ts, backend/apps/selfhosted/src/analytics/analytics.controller.ts, backend/apps/selfhosted/src/analytics/analytics.service.ts, backend/apps/selfhosted/src/analytics/utils/transformers.ts, backend/apps/selfhosted/src/common/utils.ts, backend/apps/selfhosted/src/project/project.controller.ts, backend/apps/selfhosted/src/project/project.service.ts, backend/apps/selfhosted/src/task-manager/task-manager.service.ts, backend/migrations/clickhouse/2024_06_22.js, backend/migrations/clickhouse/2024_09_10.js, backend/migrations/clickhouse/2024_10_25.js, backend/migrations/clickhouse/initialise_database.js
=> (improvement) Lower load on Clickhouse database for session duration calculations

web/public/locales/fr.json
=> add french translation

backend/apps/production/src/analytics/analytics.controller.ts, backend/apps/production/src/analytics/analytics.service.ts, backend/apps/selfhosted/src/analytics/analytics.controller.ts, backend/apps/selfhosted/src/analytics/analytics.service.ts
=> Don't store heartbeats for undefined sessions

backend/apps/cloud/src/project/project.controller.ts, backend/apps/cloud/src/project/project.service.ts, web/app/api/index.ts, web/app/pages/Dashboard/Dashboard.tsx, web/app/pages/Dashboard/PeriodSelector.tsx, web/app/pages/Dashboard/Tabs.tsx
=> (feature) Dashboard modes

backend/apps/cloud/src/analytics/analytics.controller.ts, backend/apps/cloud/src/analytics/analytics.service.ts, backend/apps/community/src/analytics/analytics.controller.ts, backend/apps/community/src/analytics/analytics.service.ts
=> fix hostname detection

backend/apps/cloud/src/project/project.controller.ts, backend/apps/cloud/src/project/project.service.ts, backend/apps/cloud/src/user/entities/user.entity.ts, backend/migrations/mysql/2025_01_11.sql, web/app/api/index.ts, web/app/lib/constants/index.ts, web/app/lib/models/User.ts, web/app/pages/Dashboard/Dashboard.tsx, web/app/pages/Dashboard/ProjectCard.tsx, web/app/pages/Project/View/utils/filters.tsx, web/public/locales/en.json
=> feature: host based dashboard navigation

web/app/pages/Captcha/Settings/CaptchaSettings.tsx, web/app/pages/Captcha/View/ViewCaptcha.helpers.tsx, web/app/pages/Dashboard/AddProject.tsx, web/app/pages/Dashboard/ProjectCard.tsx, web/app/pages/Dashboard/SortSelector.tsx, web/app/pages/Organisations/AddOrganisation.tsx, web/app/pages/Organisations/OrganisationCard.tsx, web/app/pages/Project/Alerts/Settings/ProjectAlertsSettings.tsx, web/app/pages/Project/New/index.tsx, web/app/pages/Project/Settings/ProjectSettings.tsx, web/app/pages/Project/View/Panels.tsx, web/app/pages/Project/View/ViewProject.helpers.tsx, web/app/pages/Project/View/ViewProject.tsx, web/app/pages/Project/View/components/ErrorDetails.tsx, web/app/pages/Project/View/components/Errors.tsx, web/app/pages/Project/View/components/LiveVisitorsDropdown.tsx, web/app/pages/Project/View/components/SearchFilters.tsx, web/app/pages/Project/View/components/TBPeriodSelector.tsx, web/app/pages/UserSettings/UserSettings.tsx, web/app/ui/Badge.tsx, web/app/ui/Checkbox.tsx, web/app/ui/Pagination.tsx
=> Improve font legibility

backend/.env.example, backend/Dockerfile, backend/apps/cloud/src/auth/dtos/sso-generate.dto.ts, backend/apps/community/src/auth/auth.controller.ts, backend/apps/community/src/auth/auth.service.ts, backend/apps/community/src/auth/dtos/index.ts, backend/apps/community/src/auth/dtos/oidc-auth.dto.ts, backend/apps/community/src/common/constants.ts, backend/apps/community/src/i18n/en/auth.json, backend/package-lock.json, backend/package.json, web/app/api/index.ts, web/app/components/OIDCAuth.tsx, web/app/lib/models/Auth.ts, web/app/pages/Auth/CreateNewPassword/CreateNewPassword.tsx, web/app/pages/Auth/ForgotPassword/ForgotPassword.tsx, web/app/pages/Auth/Signin/Signin.tsx, web/app/pages/Auth/Signup/Signup.tsx, web/app/pages/Auth/Socialised/index.tsx, web/app/pages/UserSettings/components/Socialisations.tsx, web/app/styles/tailwind.css, web/app/ui/Checkbox.tsx, web/public/locales/en.json
Adds OpenID Connect support to Swetrix Community Edition.
Closes
- https://github.com/Swetrix/swetrix/issues/264
=> OpenID Connect support for Swetrix Community Edition

backend/apps/cloud/src/alert/alert.controller.ts, backend/apps/cloud/src/alert/dto/alert.dto.ts, backend/apps/cloud/src/alert/entity/alert.entity.ts, backend/apps/cloud/src/integrations/telegram/telegram.service.ts, backend/apps/cloud/src/task-manager/task-manager.service.ts, backend/migrations/mysql/2025_05_10.sql, web/app/lib/constants/index.ts, web/app/lib/models/Alerts.ts, web/app/pages/Dashboard/ProjectCard.tsx, web/app/pages/Project/Alerts/Settings/ProjectAlertsSettings.tsx, web/app/pages/Project/Alerts/View/ProjectAlertsView.tsx, web/app/pages/Project/View/components/AddAViewModal.tsx, web/app/routes/feature-flags.tsx, web/public/locales/en.json
Ticket:
- https://github.com/Swetrix/swetrix/issues/336
=> (feature) Error alerts

backend/apps/cloud/src/analytics/analytics.service.ts, backend/apps/cloud/src/common/constants.ts, backend/apps/community/src/analytics/analytics.service.ts, backend/apps/community/src/common/constants.ts, web/app/lib/constants/index.ts, web/app/pages/Project/View/ViewProject.helpers.tsx, web/app/pages/Project/View/components/SearchFilters.tsx, web/app/pages/Project/View/utils/filters.tsx
=> Entry / Exit pages filters support
